spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness.user_db
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

